[package]
name = "notea"
version = "0.1.0-alpha.1"
edition = "2018"

[dependencies]
sled = "0.32.0-rc1"
anyhow = "1.0.28"
thiserror = "1.0.19"
rand = "0.7.3"
warp = "0.2.2"
bytes = "0.5.4"
tokio = { version = "0.2", features = ["macros"] }